spring:
  application:
    name: redis-srv
  datasource:
    url: jdbc:postgresql://localhost:5434/redis_db
    username: redis
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  # Redis конфигурация
  data:
    redis:
      host: localhost
      port: 6380
      username: my_user
      password:  redis
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      # Для кластера (если нужно):
      # cluster:
      #   nodes: localhost:6379,localhost:6380,localhost:6381


  #  liquibase:
#    enabled: false
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    drop-first: false  # НЕ меняйте на true в production!
#    default-schema: public
#    liquibase-schema: public
#    contexts: development

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#      continue-on-error: false

  jpa:
    hibernate:
      ddl-auto: none
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
#        order_inserts: true
#        order_updates: true
    show-sql: true
    open-in-view: false  # Отключите для лучшей производительности

# Конфигурация кэша
cache:
  redis:
#    ttl: 300  # Время жизни кэша в секундах (5 минут)
    ttl: 20  # Время жизни кэша в секундах (10 s)
    keys:
      article: "article:"


logging:
  level:
    ru.ekp.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    liquibase: INFO  # Измените на INFO для большей информации
#    org.springframework.boot.autoconfigure.liquibase: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,prometheus
      base-path: /actuator
      path-mapping:
        loggers: /loggers
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: redis-srv

server:
  port: 8080